#!/bin/bash
# Test rest interface with curl. Echo output for copy-paste to README.md

# Set port same as during install.
PORT=8004

function curl_post_train {
  echo -e "$1:\n"
  echo "    DATA='"$2"'"
  echo -ne "    # Response:\n    "
  curl -X POST -d $2 --header "Content-Type: application/json" http://localhost:$PORT/train
  echo -e "\n\n"
}

function curl_get_recommend {
  echo -e "$1:\n"
  echo "    curl -X GET http://localhost:$PORT$2"
  echo -ne "    # Response:\n    "
  curl -X GET http://localhost:$PORT/recommend$2
  echo -e "\n\n"
}



echo -e "## Example query+output\n"
echo -e "**draft**: update curl examples if I/O changes with actual recommendations.\n"
echo -e "This output is generated by `./test_dummy.sh`.\n"
echo "    Examples of responses for POST to /train/, ran as:"
echo '    curl -X POST -d $DATA --header "Content-Type: application/json" http://localhost:$PORT/train'
echo -e "\n"


echo -e "### Correct Training\n"

DATA='{"item":{"user_id":"uid","place_id":"pid","timestamp":"2014-03-03T00:00:00"}}'
curl_post_train "Item as JSON" $DATA

# Special case without application/json
echo 'Item without  `--header "Content-Type: application/json"`:'
echo -e "\n    DATA='"$DATA"'"
echo -n "    Response: "
curl -X POST -d $DATA http://localhost:$PORT/train
echo -e "\n\n"

DATA='{"extra":"extra","item":{"user_id":"uid","place_id":"pid","timestamp":"2014-03-03T00:00:00","extra":"extra"}}'
curl_post_train "Item with extra content" $DATA


echo -e "### Incorrect Training\n"

DATA='{"item_err":{"user_id":"uid","place_id":"pid","timestamp":"2014-03-03T00:00:00"}}'
curl_post_train "Missing item" $DATA

DATA='{"item":{"user_id_err":"uid","place_id":"pid","timestamp":"2014-03-03T00:00:00"}}'
curl_post_train "Missing user_id" $DATA

DATA='{"item":{"user_id":"uid","place_id_err":"pid","timestamp":"2014-03-03T00:00:00"}}'
curl_post_train "Missing place_id" $DATA

DATA='{"item":{"user_id":"uid","place_id":"pid","timestamp_err":"2014-03-03T00:00:00"}}'
curl_post_train "Missing timestamp" $DATA

#INCORRECT_TIMESTAMP='todo'
#$curl_post_train "Incorrect timestamp" $DATA
echo 'Incorrect timestamp:'
echo -e "\n    DATA='todo'"
echo -n "    Response: todo"
echo -e "\n\n"


echo -e "### Recommendations\n"

curl_get_recommend "Missing place_id" "/"

curl_get_recommend "Recommendation for some_venue_place_id" "/some_venue_place_id"

# Adding some additional data.
echo "Adding some more data to test dummy recommendation."
curl -X POST -d '{"item":{"user_id":"uid","place_id":"venue1","timestamp":"2014-03-03T00:00:00"}}' --header "Content-Type: application/json" http://localhost:$PORT/train
curl -X POST -d '{"item":{"user_id":"uid","place_id":"venue1","timestamp":"2014-03-03T00:00:00"}}' --header "Content-Type: application/json" http://localhost:$PORT/train
curl -X POST -d '{"item":{"user_id":"uid","place_id":"venue1","timestamp":"2014-03-03T00:00:00"}}' --header "Content-Type: application/json" http://localhost:$PORT/train
curl -X POST -d '{"item":{"user_id":"uid","place_id":"venue2","timestamp":"2014-03-03T00:00:00"}}' --header "Content-Type: application/json" http://localhost:$PORT/train
curl -X POST -d '{"item":{"user_id":"uid","place_id":"venue3","timestamp":"2014-03-03T00:00:00"}}' --header "Content-Type: application/json" http://localhost:$PORT/train
curl -X POST -d '{"item":{"user_id":"uid","place_id":"venue3","timestamp":"2014-03-03T00:00:00"}}' --header "Content-Type: application/json" http://localhost:$PORT/train

